### ISSUE TITLE
Fix responsiveness issues on mobile

### ISSUE THREAD

**Issue by carlisia** [gobridge/gobridge.github.io#4]
The site works fine on mobile, except that the hamburger menu (top right) is non-responsive.

**Comment by stonean** [comment]
I don’t see where bootstrap.min.js is being called or referenced. I'll take a look tonight but will check this first in case someone beats me to it.

**Comment by carlisia** [comment]
Thank you @stonean, your fix (https://github.com/gobridge/gobridge.github.io/pull/7) has been deployed. :boom:
